<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\llm-sdk\llm-sdk.csproj" />
    <ProjectReference Include="..\llm-agent\llm-agent.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>llm_ui</RootNamespace>
  </PropertyGroup>

</Project>
