<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>llm_cli</RootNamespace>
    <AssemblyName>llm</AssemblyName>
    <Version>0.5.0</Version>
    <NoWarn>OPENAI001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\llm-agent\llm-agent.csproj" />
    <ProjectReference Include="..\llm-sdk\llm-sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="help.txt" />
  </ItemGroup>

</Project>
